//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Matrimonial.Models
{
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(MetaDataUserProfile))]
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Requests = new HashSet<Request>();
            this.ShortLists = new HashSet<ShortList>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        
        public string Religion { get; set; }
        public string ProfileImage { get; set; }
        public string AnualIncome { get; set; }
        public Nullable<int> Occupation { get; set; }
        public string Employed { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string AboutUser { get; set; }
        public string Phone { get; set; }
        public string isVerified { get; set; }
        public Nullable<int> Height { get; set; }
        public string MaritalStatus { get; set; }
        public string Complexion { get; set; }
        public string BodyType { get; set; }
        public string PersonalValues { get; set; }
        public string ResidencyStatus { get; set; }
        public string WorkingWith { get; set; }
        public string ContactDetails { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual Height Height1 { get; set; }
        public virtual Occupation Occupation1 { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<ShortList> ShortLists { get; set; }
    }
}
